### ISSUE TITLE
File validation fails when building from AUR repository

### ISSUE THREAD

**Issue by nelsonb73** [ansemjo/imapfetch#5]

**Comment by ansemjo** [comment]
Huh, interesting. I have no idea of what hash that might be if not of the `0.2.2.tar.gz` .. I could swear that I checked the `PKBUILD`, too ..

**Anyway**, version `0.2.2` was not the latest in this repository regardless. I've bumped the package to version `0.2.4` and verified that the package builds fine on my machine. Please try again.

**Comment by nelsonb73** [comment]
I think i put this in the wrong place. probably needs to go to the maintaner for the AUR package, sorry..

**Comment by nelsonb73** [comment]
well, i guess not. Builds fine now. thanks!

**Comment by ansemjo** [comment]
> [...] probably needs to go to the maintaner for the AUR package, sorry..

Yeah, I *am* the maintainer of that package, so this was the right place. :blush:
